global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Jenkins metrics
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
    
    # SonarQube Community Edition doesn't support Prometheus metrics
    # This feature is only available in Data Center Edition (paid)
    # - job_name: 'sonarqube'
    #   metrics_path: '/api/monitoring/metrics'
    #   static_configs:
    #     - targets: ['sonarqube:9000']
    #   bearer_token: 'squ_10853ed7e26433c14a92f08ea597e89be226680b'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Your Backend Application (via shared network)
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']
    metrics_path: '/metrics'

  # Docker metrics via cAdvisor
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']